project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_API_TOKEN
base_url_env: CROWDIN_BASE_URL
base_path: .
preserve_hierarchy: true
files:
  [
    {
      "source": "/warp/src/main/res/values/strings.xml",
      "translation": "/warp/src/main/res/values-%two_letters_code%/strings.xml",
      "languages_mapping":
        { "two_letters_code": { "nb": "nb", "fi": "fi", "da": "da", "sv": "sv" } },
      "type": "android",
    },
  ]
