pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
        mavenLocal()
    }
}
dependencyResolutionManagement {
    @Suppress("UnstableApiUsage")
    repositoriesMode.set(RepositoriesMode.PREFER_PROJECT)
    @Suppress("UnstableApiUsage")
    repositories {
        google()
        mavenCentral()
        mavenLocal()
    }
}
rootProject.name = "Warp app"
include(":app")
include(":snapshot-test-utils")
include(":snapshot-alert")
include(":snapshot-badge")
include(":snapshot-box")
include(":snapshot-button")
include(":snapshot-callout")
include(":snapshot-checkbox")
include(":snapshot-datepicker")
include(":snapshot-divider")
include(":snapshot-expandable")
include(":snapshot-icons")
include(":snapshot-link")
include(":snapshot-logo")
include(":snapshot-navigationbar")
include(":snapshot-pageindicator")
include(":snapshot-pill")
include(":snapshot-popover")
include(":snapshot-radio")
include(":snapshot-rangeslider")
include(":snapshot-select")
include(":snapshot-slider")
include(":snapshot-snackbar")
include(":snapshot-spinner")
include(":snapshot-state")
include(":snapshot-switch")
include(":snapshot-tabs")
include(":snapshot-textfield")
include(":snapshot-toast")
include(":snapshot-tooltip")
include(":snapshot-topappbar")
include(":warp")
include(":warp-blocket")
include(":warp-dba")
include(":warp-finn")
include(":warp-tori")
include(":warp-vend")
include(":warp-neutral")
