package com.schibsted.nmp.warpapp.ui

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.Dp
import com.schibsted.nmp.warp.components.WarpIcon
import com.schibsted.nmp.warp.theme.WarpIconResource
import com.schibsted.nmp.warp.theme.WarpResources.icons
import com.schibsted.nmp.warp.theme.WarpTheme
import com.schibsted.nmp.warp.theme.WarpTheme.dimensions


@Composable
fun IconScreen(onUp: () -> Unit) {
    DetailsScaffold(title = "Icons", onUp = onUp) {
        IconScreenContent()
    }
}

@Composable
private fun IconScreenContent() {
    Row(
        modifier = Modifier
            .verticalScroll(rememberScrollState())
            .fillMaxWidth(),
        horizontalArrangement = Arrangement.SpaceEvenly,
    ) {
        Column(
            verticalArrangement = Arrangement.spacedBy(dimensions.space2),
            modifier = Modifier

                .padding(dimensions.space2)
        ) {
            CreateIcons(dimensions.icon.small)
        }
        Column(
            verticalArrangement = Arrangement.spacedBy(dimensions.space2),
            modifier = Modifier
                .padding(dimensions.space2)
        ) {
            CreateIcons(dimensions.icon.default)
        }
        Column(
            verticalArrangement = Arrangement.spacedBy(dimensions.space2),
            modifier = Modifier
                .padding(dimensions.space2)
        ) {
            CreateIcons(dimensions.icon.large)
        }
    }
}

@Composable
fun CreateIcons(size: Dp) {
    CreateIcon(icons.activeAds, size)
    CreateIcon(icons.ads, size)
    CreateIcon(icons.airCon, size)
    CreateIcon(icons.airplaneBed, size)
    CreateIcon(icons.allWheelDrive, size)
    CreateIcon(icons.animalPaw, size)
    CreateIcon(icons.archiveBox, size)
    CreateIcon(icons.archway, size)
    CreateIcon(icons.arrowDown, size)
    CreateIcon(icons.arrowLeft, size)
    CreateIcon(icons.arrowRight, size)
    CreateIcon(icons.arrowUp, size)
    CreateIcon(icons.paperclip, size)
    CreateIcon(icons.gearAutomatic, size)
    CreateIcon(icons.awardMedal, size)
    CreateIcon(icons.backWheelDrive, size)
    CreateIcon(icons.bag, size)
    CreateIcon(icons.bank, size)
    CreateIcon(icons.bankIdNo, size)
    CreateIcon(icons.batteryEmpty, size)
    CreateIcon(icons.batteryFull, size)
    CreateIcon(icons.batteryHalfFull, size)
    CreateIcon(icons.beach, size)
    CreateIcon(icons.bell, size)
    CreateIcon(icons.bellFilled, size)
    CreateIcon(icons.bin, size)
    CreateIcon(icons.block, size)
    CreateIcon(icons.boat, size)
    CreateIcon(icons.bolt, size)
    CreateIcon(icons.bookmark, size)
    CreateIcon(icons.briefcaseUser, size)
    CreateIcon(icons.briefcase, size)
    CreateIcon(icons.browser, size)
    CreateIcon(icons.browserVerified, size)
    CreateIcon(icons.building, size)
    CreateIcon(icons.buildingPlot, size)
    CreateIcon(icons.bulb, size)
    CreateIcon(icons.burger, size)
    CreateIcon(icons.bus, size)
    CreateIcon(icons.cabinHut, size)
    CreateIcon(icons.calculator, size)
    CreateIcon(icons.calendar, size)
    CreateIcon(icons.calendarBlank, size)
    CreateIcon(icons.calendarPlus, size)
    CreateIcon(icons.camera, size)
    CreateIcon(icons.cancel, size)
    CreateIcon(icons.car, size)
    CreateIcon(icons.carLeft, size)
    CreateIcon(icons.carPart, size)
    CreateIcon(icons.carRent, size)
    CreateIcon(icons.carRight, size)
    CreateIcon(icons.chair, size)
    CreateIcon(icons.charger, size)
    CreateIcon(icons.charter, size)
    CreateIcon(icons.chatSupport, size)
    CreateIcon(icons.check, size)
    CreateIcon(icons.checkList, size)
    CreateIcon(icons.checkShield, size)
    CreateIcon(icons.chevronDoubleLeft, size)
    CreateIcon(icons.chevronDoubleRight, size)
    CreateIcon(icons.chevronDown, size)
    CreateIcon(icons.chevronLeft, size)
    CreateIcon(icons.chevronRight, size)
    CreateIcon(icons.chevronUp, size)
    CreateIcon(icons.circlePlus, size)
    CreateIcon(icons.circlePlusFilled, size)
    CreateIcon(icons.circleUser, size)
    CreateIcon(icons.circleUserFilled, size)
    CreateIcon(icons.clock, size)
    CreateIcon(icons.clockCountDown, size)
    CreateIcon(icons.close, size)
    CreateIcon(icons.code, size)
    CreateIcon(icons.cog, size)
    CreateIcon(icons.colorPalette, size)
    CreateIcon(icons.confetti, size)
    CreateIcon(icons.cookie, size)
    CreateIcon(icons.creditCard, size)
    CreateIcon(icons.cursor, size)
    CreateIcon(icons.delivery, size)
    CreateIcon(icons.deliveryKey, size)
    CreateIcon(icons.diner, size)
    CreateIcon(icons.discount, size)
    CreateIcon(icons.dislike, size)
    CreateIcon(icons.door, size)
    CreateIcon(icons.dots, size)
    CreateIcon(icons.dotsVertical, size)
    CreateIcon(icons.doubleBed, size)
    CreateIcon(icons.download, size)
    CreateIcon(icons.dragDots, size)
    CreateIcon(icons.draw, size)
    CreateIcon(icons.drawer, size)
    CreateIcon(icons.drill, size)
    CreateIcon(icons.drink, size)
    CreateIcon(icons.edit, size)
    CreateIcon(icons.energy, size)
    CreateIcon(icons.engine, size)
    CreateIcon(icons.engineBelt, size)
    CreateIcon(icons.error, size)
    CreateIcon(icons.exchange, size)
    CreateIcon(icons.expand, size)
    CreateIcon(icons.eyeOff, size)
    CreateIcon(icons.eyeOn, size)
    CreateIcon(icons.facebook, size)
    CreateIcon(icons.farm, size)
    CreateIcon(icons.fileAdd, size)
    CreateIcon(icons.fileArrowDown, size)
    CreateIcon(icons.filter, size)
    CreateIcon(icons.fireplace, size)
    CreateIcon(icons.fishing, size)
    CreateIcon(icons.dumbbell, size)
    CreateIcon(icons.frontWheelDrive, size)
    CreateIcon(icons.gamingController, size)
    CreateIcon(icons.gasDiesel, size)
    CreateIcon(icons.gasFuel, size)
    CreateIcon(icons.gasHybrid, size)
    CreateIcon(icons.graphLine, size)
    CreateIcon(icons.graphPie, size)
    CreateIcon(icons.grid, size)
    CreateIcon(icons.grill, size)
    CreateIcon(icons.guitar, size)
    CreateIcon(icons.headset, size)
    CreateIcon(icons.heart, size)
    CreateIcon(icons.heartRate, size)
    CreateIcon(icons.hiking, size)
    CreateIcon(icons.history, size)
    CreateIcon(icons.house, size)
    CreateIcon(icons.houseBed, size)
    CreateIcon(icons.houseFilled, size)
    CreateIcon(icons.houseModern, size)
    CreateIcon(icons.housePerson, size)
    CreateIcon(icons.iceSkater, size)
    CreateIcon(icons.image, size)
    CreateIcon(icons.info, size)
    CreateIcon(icons.instagram, size)
    CreateIcon(icons.jetSki, size)
    CreateIcon(icons.key, size)
    CreateIcon(icons.lamp, size)
    CreateIcon(icons.landscape, size)
    CreateIcon(icons.washingMachine, size)
    CreateIcon(icons.layers, size)
    CreateIcon(icons.leaf, size)
    CreateIcon(icons.lift, size)
    CreateIcon(icons.like, size)
    CreateIcon(icons.link, size)
    CreateIcon(icons.linkExternal, size)
    CreateIcon(icons.listNumbers, size)
    CreateIcon(icons.listSort, size)
    CreateIcon(icons.lockShield, size)
    CreateIcon(icons.logout, size)
    CreateIcon(icons.luggage, size)
    CreateIcon(icons.mail, size)
    CreateIcon(icons.mailbox, size)
    CreateIcon(icons.gearManual, size)
    CreateIcon(icons.geometricShapes, size)
    CreateIcon(icons.globe, size)
    CreateIcon(icons.map, size)
    CreateIcon(icons.messages, size)
    CreateIcon(icons.messagesFilled, size)
    CreateIcon(icons.minus, size)
    CreateIcon(icons.mixer, size)
    CreateIcon(icons.money, size)
    CreateIcon(icons.moon, size)
    CreateIcon(icons.motorcycle, size)
    CreateIcon(icons.mountain, size)
    CreateIcon(icons.noSmoking, size)
    CreateIcon(icons.officeDesk, size)
    CreateIcon(icons.organize, size)
    CreateIcon(icons.parking, size)
    CreateIcon(icons.phone, size)
    CreateIcon(icons.phoneCheck, size)
    CreateIcon(icons.phoneScratched, size)
    CreateIcon(icons.phoneUsed, size)
    CreateIcon(icons.pictureStack, size)
    CreateIcon(icons.pinMarker, size)
    CreateIcon(icons.pinRound, size)
    CreateIcon(icons.planeLand, size)
    CreateIcon(icons.planeTakeOff, size)
    CreateIcon(icons.ticket, size)
    CreateIcon(icons.play, size)
    CreateIcon(icons.playhouse, size)
    CreateIcon(icons.plus, size)
    CreateIcon(icons.rocket, size)
    CreateIcon(icons.productBump, size)
    CreateIcon(icons.productCarousel, size)
    CreateIcon(icons.productHighlightListing, size)
    CreateIcon(icons.productNaBolagsProfil, size)
    CreateIcon(icons.megaphone, size)
    CreateIcon(icons.productStarred, size)
    CreateIcon(icons.productTop, size)
    CreateIcon(icons.propeller, size)
    CreateIcon(icons.question, size)
    CreateIcon(icons.refresh, size)
    CreateIcon(icons.roomService, size)
    CreateIcon(icons.rotateLeft, size)
    CreateIcon(icons.rotateRight, size)
    CreateIcon(icons.rowingBoat, size)
    CreateIcon(icons.ruler, size)
    CreateIcon(icons.sauna, size)
    CreateIcon(icons.scrollUp, size)
    CreateIcon(icons.search, size)
    CreateIcon(icons.seat, size)
    CreateIcon(icons.send, size)
    CreateIcon(icons.wrench, size)
    CreateIcon(icons.share, size)
    CreateIcon(icons.shipping, size)
    CreateIcon(icons.shirt, size)
    CreateIcon(icons.shoes, size)
    CreateIcon(icons.shoppingCart, size)
    CreateIcon(icons.shovel, size)
    CreateIcon(icons.shower, size)
    CreateIcon(icons.shrink, size)
    CreateIcon(icons.sidebarChevronLeft, size)
    CreateIcon(icons.sidebarChevronRight, size)
    CreateIcon(icons.singleCylinder, size)
    CreateIcon(icons.skyscraper, size)
    CreateIcon(icons.smileyGood, size)
    CreateIcon(icons.smileyHappy, size)
    CreateIcon(icons.smileyNeutral, size)
    CreateIcon(icons.smileySad, size)
    CreateIcon(icons.sofa, size)
    CreateIcon(icons.sorting, size)
    CreateIcon(icons.lotusFlower, size)
    CreateIcon(icons.sparkles, size)
    CreateIcon(icons.speedometer, size)
    CreateIcon(icons.stairs, size)
    CreateIcon(icons.starCheck, size)
    CreateIcon(icons.starEmpty, size)
    CreateIcon(icons.starFull, size)
    CreateIcon(icons.starHalf, size)
    CreateIcon(icons.store, size)
    CreateIcon(icons.storeFront, size)
    CreateIcon(icons.stove, size)
    CreateIcon(icons.stroller, size)
    CreateIcon(icons.success, size)
    CreateIcon(icons.suitcase, size)
    CreateIcon(icons.suitcaseTrolley, size)
    CreateIcon(icons.sun, size)
    CreateIcon(icons.support, size)
    CreateIcon(icons.swimming, size)
    CreateIcon(icons.tag, size)
    CreateIcon(icons.taskList, size)
    CreateIcon(icons.textBold, size)
    CreateIcon(icons.textHOne, size)
    CreateIcon(icons.textItalic, size)
    CreateIcon(icons.textStrikethrough, size)
    CreateIcon(icons.textUnderline, size)
    CreateIcon(icons.theater, size)
    CreateIcon(icons.threeSixty, size)
    CreateIcon(icons.townhouse, size)
    CreateIcon(icons.tractor, size)
    CreateIcon(icons.trendDown, size)
    CreateIcon(icons.trendFlat, size)
    CreateIcon(icons.trendUp, size)
    CreateIcon(icons.tshirt, size)
    CreateIcon(icons.tv, size)
    CreateIcon(icons.x, size)
    CreateIcon(icons.up, size)
    CreateIcon(icons.upload, size)
    CreateIcon(icons.user, size)
    CreateIcon(icons.userGroup, size)
    CreateIcon(icons.users, size)
    CreateIcon(icons.vacuum, size)
    CreateIcon(icons.vase, size)
    CreateIcon(icons.verification, size)
    CreateIcon(icons.wallet, size)
    CreateIcon(icons.warning, size)
    CreateIcon(icons.warranty, size)
    CreateIcon(icons.waterPitcher, size)
    CreateIcon(icons.weight, size)
    CreateIcon(icons.wheelchair, size)
    CreateIcon(icons.wifi, size)
    CreateIcon(icons.tree, size)
    CreateIcon(icons.youtube, size)
    CreateIcon(icons.microphone, size)
    CreateIcon(icons.microphoneSlash, size)
    CreateIcon(icons.translate, size)
    CreateIcon(icons.scale, size)
    CreateIcon(icons.phoneHandset, size)
}

@Composable
private fun CreateIcon(icon: WarpIconResource, size: Dp) {
    WarpIcon(
        icon = icon,
        color = WarpTheme.colors.icon.primary,
        size = size
    )
}