object Versions {
    const val jvm = "1.8"
    const val kotlin = "1.9.22"
    const val kotlinCompiler = "1.5.8"
    const val core = "1.9.0"
    const val compose = "2023.06.01"
    const val constraintLayout = "1.0.1"
    const val appCompat = "1.4.1"
    const val junit = "5.10.0"
    const val junitJupiter = "4.13.2"
    const val extJunit = "1.1.3"
    const val espressoCore = "3.4.0"
    const val koin = "3.5.0"
    const val navigationCompose = "2.6.0"
    const val material = "1.5.0"
    const val googleServices = "4.4.0"
    const val paparazzi = "1.3.4"
    const val composeActivity = "1.8.2"
    const val testParameterInjector = "1.9"
    const val kotest = "5.3.1"
}